spring:
  application:
    name: restSpringBoot
  datasource: # configures the connection pool
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livraria?useTimeZone=true&serverTimezone=UTC
    username: weber
    password: guiebiju
  jpa: # configures the JPA provider
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      show_sql: false
    open-in-view: false # disables the OpenEntityManagerInViewFilter